[project]
name = "03p-facial-expression-recoginition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Faizy", email = "34925947+mohd-faizy@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "jupyter>=1.1.1",
    "livelossplot>=0.6.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "opencv-python<5",
    "seaborn>=0.13.2",
    "tensorflow>=2.21.0",
]

[project.scripts]
03p-facial-expression-recoginition = "03p_facial_expression_recoginition:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
